### PR TITLE
fix: Statistics be refreshed on each mount and prevent wrong values

### PR DESCRIPTION
**Pull request by FedeMadoery**
# Description

Fix dateUtils to return "-" and validate zero as strings
Update queries to be revalidated on mount

Validating the 0 as a string, we prevent the following behavior

Before:
image

After:
image

### CODE REVIEW

**Comment by ramabit** [comment]
@FedeMadoery I had improved that in another branch I just merged, putting that if there are no challenges it says '0 challenges'. And the same for the badges created in the creator profile. Take a look there, test it and choose which option you find better. If you find mines better, we don't need this PR. If you find yours better, you need to fix the conflicts here.

**Review by ramabit — CHANGES_REQUESTED** [review]
check my commer above

**Comment by FedeMadoery** [comment]
> @FedeMadoery I had improved that in another branch I just merged, putting that if there are no challenges it says '0 challenges'. And the same for the badges created in the creator profile. Take a look there, test it and choose which option you find better. If you find mines better, we don't need this PR. If you find yours better, you need to fix the conflicts here.

I will merge your changes into this branch and check that, thanks for the advice

**Review by ramabit — CHANGES_REQUESTED** [review]
@FedeMadoery 
Screenshot 2023-10-06 at 18 18 23
this "- without received challenges" is not understandable.
In my opinion we should not show this if there are no challenges received. The "0 challenges received" is already enough.
Another question is about the unit of time in case there are challenges. Are always days? from what I see in the code dayjs could send unit in months or years.

**Pull request merged**
